"""add_extracted_metadata_json_column_and_statuses

Revision ID: 3af274d4c1f4
Revises: cf3f0678d3be
Create Date: 2025-05-08 09:10:51.154687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af274d4c1f4'
down_revision: Union[str, None] = 'cf3f0678d3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
