"""add_extracted_text_path_and_update_enums

Revision ID: 5b8aa0f0ab87
Revises: 0b1b19de2e2d
Create Date: 2025-05-07 15:34:51.606992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8aa0f0ab87'
down_revision: Union[str, None] = '0b1b19de2e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text_path', sa.String(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('UPLOADED', 'OCR_PENDING', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', 'NER_PENDING', 'NER_PROCESSING', 'NER_COMPLETED', 'NER_FAILED', 'APPROVED', 'REJECTED', name='documentstatusenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('UPLOADED', 'OCR_PENDING', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', 'NER_PENDING', 'NER_PROCESSING', 'NER_COMPLETED', 'NER_FAILED', 'APPROVED', 'REJECTED', name='documentstatusenum'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('extracted_text_path')

    # ### end Alembic commands ###
