"""add_extracted_text_path_and_update_enums

Revision ID: ba28f0f74926
Revises: 5b8aa0f0ab87
Create Date: 2025-05-07 16:01:51.384920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba28f0f74926'
down_revision: Union[str, None] = '5b8aa0f0ab87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
