"""add_extracted_metadata_json_column_and_statuses

Revision ID: cf3f0678d3be
Revises: d7a66ff9ff0c
Create Date: 2025-05-08 09:03:58.596039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cf3f0678d3be'
down_revision: Union[str, None] = 'd7a66ff9ff0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_metadata', sqlite.JSON(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('UPLOADED', 'OCR_PENDING', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', 'EXTRACT_PENDING', 'EXTRACT_PROCESSING', 'EXTRACT_COMPLETED', 'EXTRACT_FAILED', 'APPROVED', 'REJECTED', name='documentstatusenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('UPLOADED', 'OCR_PENDING', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', 'EXTRACT_PENDING', 'EXTRACT_PROCESSING', 'EXTRACT_COMPLETED', 'EXTRACT_FAILED', 'APPROVED', 'REJECTED', name='documentstatusenum'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
        batch_op.drop_column('extracted_metadata')

    # ### end Alembic commands ###
