"""add_extracted_text_path_and_update_enums

Revision ID: d7a66ff9ff0c
Revises: ba28f0f74926
Create Date: 2025-05-07 16:47:10.076969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a66ff9ff0c'
down_revision: Union[str, None] = 'ba28f0f74926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
